### ISSUE TITLE
如何判断小车到达S弯，如何排除非S弯因素

### ISSUE THREAD

**Issue by zc6666666** [xushu-me/qingzhou-unet#1]
请问如何知道小车已经到达了S弯，不管哪张图都会返回一个结果，这导致了我无法判断S弯的开始和结束，望指教

**Comment by xushu-me** [comment]
> 请问如何知道小车已经到达了S弯，不管哪张图都会返回一个结果，这导致了我无法判断S弯的开始和结束，望指教

s弯的起点在地图上的坐标和停车的方向是确定的，所以不需要判断到达，直接设置让车开到固定坐标就行了，然后再执行s弯的任务。判断结束就判断图像里是否还有车道线，我们当时超过3帧没有车道线就算结束。

**Comment by zc6666666** [comment]
> > 请问如何知道小车已经到达了S弯，不管哪张图都会返回一个结果，这导致了我无法判断S弯的开始和结束，望指教
> 
> s弯的起点在地图上的坐标和停车的方向是确定的，所以不需要判断到达，直接设置让车开到固定坐标就行了，然后再执行s弯的任务。判断结束就判断图像里是否还有车道线，我们当时超过3帧没有

**Comment by zc6666666** [comment]
> > 请问如何知道小车已经到达了S弯，不管哪张图都会返回一个结果，这导致了我无法判断S弯的开始和结束，望指教
> 
> s弯的起点在地图上的坐标和停车的方向是确定的，所以不需要判断到达，直接设置让车开到固定坐标就行了，然后再执行s弯的任务。判断结束就判断图像里是否还有车道线，我们当时超过3帧没有车道线就算结束。

我对上述的理解是用上位机开到S弯入口，然后开始视觉识别，对于判断图像里是否还有车道线这部分可以再详细一点吗，这个模型对每张图片都会产生结果，没有s弯也会出现杂七杂八的点，请问是如何判断的
